### PR TITLE
Support for postcss.config.js

### PR DESCRIPTION
**Pull request by SimeonGriggs**
Awesome script! 

I had a need to insert an additional two PostCSS plugins into my Tailbuild.

This _works_ but I'm not sure the syntax is something you'd be happy with. Just starting the discussion at least.

### CODE REVIEW

**Comment by SimeonGriggs** [comment]
Actually the more I think on it, perhaps this should be more like the use of a `tailwind.config.js` file in that it supersedes the function's own settings. As in, it's your responsibility to include `tailwindcss` and `autoprefixer` plugins.

**Comment by calebporzio** [comment]
What plugins are you trying to load?

**Comment by SimeonGriggs** [comment]
CSS Next.

I was using Tailbuild to use Tailwind CSS on the fly in an application that can import raw CSS but gives no access to the webpack/postcss config. And its CSS Variables use `color` functions, which required CSS Next to load.

**Comment by calebporzio** [comment]
Yeah, I'd say at that point it might just be easier to run the build using standard bundlers. Thanks for following up, but going to close this...

**Pull request closed without merging**
